const states = [
  { name: "Alabama", initials: "AL" },
  { name: "Alaska", initials: "AK" },
  { name: "American", intials: "AS" },
  { name: "Arizona", initials: "AZ" },
  { name: "Arkansas", initials: "AR" },
  { name: "California", initials: "CA" },
  { name: "Colorado", initials: "CO" },
  { name: "Conneticut", initials: "AL" },
  { name: "Delaware", initials: "DE" },
  { name: "Florida", initals: "FL" },
  { name: "Georgia", initials: "GA" },
  { name: "Guam", initials: "GU" },
  { name: "Hawaii", initals: "HI" },
  { name: "Idaho", initals: "ID" },
  { name: "Illinois", initials: "IL" },
  { name: "Indiana", initials: "IN" },
  { name: "Iowa", initals: "IA" },
  { name: "Kansas", initials: "KS" },
  { name: "Kentucky", initials: "KY" },
  { name: "Lousiana", initals: "LA" },
  { name: "Maine", initials: "ME" },
  { name: "Maryland", initials: "MD" },
  { name: "Marshall Islands", initals: "MH" },
  { name: "Massachusetts", initials: "MA" },
  { name: "Michigan", initials: "MI" },
  { name: "Micronesia", initials: "FM" },
  { name: "Minnesota", initals: "MN" },
  { name: "Mississippi", initials: "MS" },
  { name: "Missouri", initials: "MO" },
  { name: "Montana", initals: "MT" },
  { name: "Nebraska", initials: "NE" },
  { name: "Nevada", initials: "NV" },
  { name: "New Hampshire", initals: "NH" },
  { name: "New Jersey", initials: "NJ" },
  { name: "New Mexico", initials: "NM" },
  { name: "New York", initals: "NY" },
  { name: "North Carolina", initials: "NC" },
  { name: "North Dakota", initials: "ND" },
  { name: "Northern Marianas", initals: "MP" },
  { name: "Ohio", initials: "OH" },
  { name: "Oklahoma", initials: "OK" },
  { name: "Oregon", initials: "OR" },
  { name: "Palau", initals: "PW" },
  { name: "Pennsylvania", initials: "PA" },
  { name: "Puerto Rico", initials: "PR" },
  { name: "Rhode Island", initals: "RI" },
  { name: "South Carolina", initials: "SC" },
  { name: "South Dakota", initials: "SD" },
  { name: "Tennessee", initals: "TN" },
  { name: "Texas", initials: "TX" },
  { name: "Utah", initials: "UT" },
  { name: "Vermont", initals: "VT" },
  { name: "Virginia", initials: "VA" },
  { name: "Virgin Islands", initials: "VI" },
  { name: "Washington", initials: "WA" },
  { name: "West Virginia", initals: "WV" },
  { name: "Wisconsin", initials: "WI" },
  { name: "Wyoming", initials: "WY" }
];

export default states;
